/**
 * SEO keyword bank — sourced from the client's keyword research sheet
 * ("Keyword / Avg. monthly searches"). Struck-out keywords were excluded.
 * Grouped by search intent, highest-volume groups first.
 */

/* ── Core ABA — high volume (~5,000 / month) ── */
const CORE_ABA_KEYWORDS = [
  "analytical behavior analysis",
  "autism behavior treatment",
  "applied analysis behavior",
  "applied behavior analysis aba",
  "applied behavior analysis aba autism",
  "applied behavior autism",
  "autism behaviour analysis",
  "behavior analysis aba",
  "intensive behavioural intervention",
  "aba services for autism",
  "autism applied behavior analysis",
  "aba th",
  "applied behavior analysis treatment",
  "speech language therapy autism",
  "autism and applied behavior analysis",
];

/* ── ABA — medium volume (~500 / month) ── */
const ABA_MID_VOLUME_KEYWORDS = [
  "aba services",
  "applied behavior analysis near me",
  "aba behavior",
  "aba analysis",
  "aba behaviour",
  "examples of applied behavior analysis",
  "aba near me",
  "speech therapy for autism near me",
  "best therapy for autism",
  "best autism treatment in india",
  "therapy for autism spectrum disorder",
  "asd aba",
  "ot and autism",
  "best treatment for autism spectrum disorder",
];

/* ── ABA services, therapy & programs ── */
const ABA_SERVICE_KEYWORDS = [
  "aba therapy training",
  "aba company",
  "aba providers",
  "aba evaluation",
  "applied behavior services",
  "aba interventions",
  "aba strategies",
  "applied aba",
  "adult aba therapy",
  "aba early intervention",
  "aba agencies",
  "aba learning center",
  "aba service providers",
  "aba helps",
  "aba strategies for autism",
  "aba approach",
  "aba early intervention programs",
  "aba interventions for elopement",
  "early aba",
  "aba support",
  "private aba services",
  "aba specialists",
  "aba therapy for aggressive behavior",
  "applied behavior analysis for adults",
  "aba can help",
  "aba behavior services",
  "aba care",
  "aba meaning therapy",
  "bcba services",
  "understanding aba therapy",
  "aba therapy goals",
  "aba behavior management strategies",
  "comprehensive aba therapy",
  "aba today",
  "aba websites",
  "aba vb therapy",
  "applied behavior analysis companies",
  "aba for dummies",
  "aba for aspergers",
  "autism & behavior services",
  "aba preschools",
  "aba social skills",
  "aba spectrum therapy",
  "aba behavior solutions",
  "aba therapy interventions",
  "aba treatment center",
  "aba is",
  "applied behavior analysis center",
  "aba therapy only for autism",
  "learning aba",
  "aba sessions",
  "medical aba services",
  "behavior analysis and intervention center",
  "aba overview",
  "social skills aba",
  "clinic aba",
  "behavior in aba",
  "aba stands for autism",
  "aba verbal behavior",
  "applied behavior intervention",
  "positive aba",
  "applied behavior analysis providers",
  "applied behavior analysis clinic",
  "aba trained",
  "learning with aba",
  "advanced aba",
  "aba behavior interventions",
  "applied behavior analysis interventions",
  "positive reinforcement for autism",
  "life skills aba",
  "aba applied behavior analysis therapy",
  "aba behavior strategies",
  "aba behavior therapies & testing",
  "aba behavior therapies and testing",
  "aba behaviour management",
  "aba effective services",
  "aba interventions for aggressive behavior",
  "aba is based on",
  "aba is what",
  "aba treatment plan for autism",
  "aba therapy and ptsd",
  "applied behavior analysis benefits",
  "applied behavior analysis early intervention",
  "applied behavior analysis in practice",
  "applied behavior analysis occupational therapy",
  "applied behavior analysis of language and cognition",
  "applied behavior analysis strategies",
  "applied treatment analysis",
  "behavior treatment analysis",
  "behavior treatment and analysis",
  "benefits of applied behavior analysis",
  "cost of applied behavior analysis for autism",
  "in aba",
  "intervention in aba",
  "principles of applied behaviour analysis",
  "aba therapy home services",
  "aba program for autism",
  "aba in home services",
  "aba pediatric",
  "aba cost",
  "aba therapy locations",
  "aba therapy age range",
  "aba occupational therapy",
  "best aba",
  "aba day program",
  "aba help",
  "aba doctor",
  "aba special needs",
  "aba therapy is",
  "que es aba therapy",
  "aba facilities",
  "aba therapeutics",
  "aba ot",
  "aba therapy session for autism",
  "ot and aba",
  "aba age range",
  "applied behavior analysis cost",
  "aba hospital",
  "aba age",
  "speech aba",
  "virtual aba services",
  "behavior analysis for autism",
];

/* ── ABA methods & clinical techniques ── */
const ABA_METHOD_KEYWORDS = [
  "abi therapy",
  "eibi therapy",
  "eibi therapy near me",
  "verbal behavior approach aba",
  "applied verbal behavior",
  "applied behavior analysis discrete trial training",
  "applied behavior analysis evidence based practice",
  "evidence based practice applied behavior analysis",
  "functional communication training aba examples",
  "contingency management aba",
  "visual supports aba",
  "floor time aba",
  "play aba",
  "play skills aba",
  "applied behavior analysis lovaas",
  "ivar lovaas aba",
  "lovaas method aba",
  "lovaas therapy",
  "lovaas treatment",
  "jasper aba",
];

/* ── Local intent — "near me" searches ── */
const NEAR_ME_KEYWORDS = [
  "aba companies near me",
  "aba providers near me",
  "aba agencies near me",
  "action behavior centers near me",
  "action behavior center near me",
  "aba evaluation near me",
  "aba home services near me",
  "bcba therapist near me",
  "intensive aba therapy near me",
  "aba places near me",
  "aba specialist near me",
  "bcba services near me",
  "behavior analysis near me",
  "bcbas near me",
  "aba services near me",
  "aba center near me",
  "aba in home therapy near me",
  "home based aba therapy near me",
  "aba autism therapy near me",
  "aba service near me",
  "aba schools for autism near me",
  "best aba services near me",
  "aba company near me",
  "aba program near me",
  "aba centres near me",
  "aba therapy agencies near me",
  "autism facilities near me",
  "aba facilities near me",
  "behavioural therapy for autism near me",
  "aba testing near me",
  "best aba companies near me",
  "autism agency near me",
  "aba provider near me",
];

/* ── Autism treatment, therapy & centres ── */
const AUTISM_CARE_KEYWORDS = [
  "applied behavior center for autism",
  "the applied behavior center for autism",
  "applied center for autism",
  "center for applied behavior analysis",
  "institute for applied behavior analysis",
  "center for autism & behavior analysis",
  "behavior analysis center for autism",
  "behavior center for autism",
  "therapy center for autism",
  "best therapy center for autism",
  "autism therapy providers",
  "autism treatment center in india",
  "autism centers in india",
  "autism centre in delhi",
  "most effective treatment for autism spectrum disorder",
  "treatment options for asd",
  "best for autism",
  "autism online therapy",
  "autism in home services",
  "autism facility",
  "autism company",
  "early autism solutions",
  "early autism service",
  "autism early learning center",
  "behavioral learning center",
  "therapy for autistic teenager",
  "autism therapy for parents",
  "sunshine program autism",
  "sunshine autism",
  "international center for autism and neurodevelopment",
  "autism speaks applied behavior analysis",
  "handbook of applied behavior analysis interventions for autism",
];

/* ── Speech & occupational therapy for autism ── */
const SPEECH_OT_KEYWORDS = [
  "speech and occupational therapy for autism",
  "speech therapy interventions for autism",
  "speech therapy ideas for autism",
  "ot services for autism",
  "behavior speech therapy",
  "spectrum ot",
];

/* ── Parents, teachers & ABA careers ── */
const TRAINING_CAREER_KEYWORDS = [
  "aba behavior therapist",
  "aba resources for parents",
  "aba parent education",
  "applied behavior analysis for parents",
  "applied behavior analysis for dummies",
  "parent training applied behavior analysis",
  "aba therapy training for teachers",
  "looking for aba therapist",
  "find an aba therapist",
  "skills for aba therapist",
  "skills needed for aba therapist",
  "skills of an aba therapist",
  "working as an aba therapist",
  "lead aba therapist",
  "aba instructor therapist",
  "behavior technician aba therapy",
  "teaching aba",
  "aba approach to teaching",
  "aba teaching procedures",
];

/* ── Provider / brand-name searches ── */
const PROVIDER_NAME_KEYWORDS = [
  "attain aba",
  "bluesprig pediatrics",
  "bluesprig aba",
  "acorn aba",
  "in bloom aba",
  "abc autism therapy",
  "able aba therapy",
  "able aba services",
  "spark aba therapy",
  "kaleidoscope aba therapy",
  "easter seals aba",
  "the helm aba",
  "bci aba",
  "butterfly aba",
  "seacoast aba",
  "triangle aba",
  "yellowbus aba",
  "key aba",
  "keyaba",
  "aba squad",
  "you & us aba services",
  "aba programming inc",
  "trellis aba",
  "trellis aba services",
  "collaborative aba services",
  "collaborative aba services llc",
  "epic aba therapy",
  "aba unlimited",
  "promise aba",
  "aba collective",
  "lifespan aba",
  "constellations aba",
  "essential aba",
  "black applied behavior analysis",
  "settle down aba",
  "aba 4",
  "aba associates llc",
  "aba behavioral group llc",
  "aba blue",
  "aba connection",
  "abai aba",
  "air aba",
  "applied behavior analysis today inc",
  "aptus aba services",
  "bay aba",
  "care aba",
  "climb aba",
  "common thread aba",
  "impact aba services",
  "learning skills aba academy for autism & special needs",
  "mobile bay aba autism center",
  "my world aba",
  "new heights aba",
  "new leaf autism & aba",
  "quartet behavioral spectrum services",
  "riley aba",
  "spectrum aba services",
  "steps aba services",
  "we are unique aba",
  "sunshine aba",
  "aba sunshine",
  "keys autism",
  "proven aba",
  "continuum aba",
  "learning continuum aba",
  "focus aba",
  "aba star",
];

export const SEO_KEYWORDS = [
  ...CORE_ABA_KEYWORDS,
  ...ABA_MID_VOLUME_KEYWORDS,
  ...ABA_SERVICE_KEYWORDS,
  ...ABA_METHOD_KEYWORDS,
  ...NEAR_ME_KEYWORDS,
  ...AUTISM_CARE_KEYWORDS,
  ...SPEECH_OT_KEYWORDS,
  ...TRAINING_CAREER_KEYWORDS,
  ...PROVIDER_NAME_KEYWORDS,
];
